### ISSUE TITLE
Installation and Setup Error

### ISSUE THREAD

**Issue by gutter007** [maxrossello/redmine_app_timesheets#40] opened 2014-12-15 16:36 UTC
During Installation I got the following error:
an error has occurred, this and all later migrations canceled:

unknown attribute: description/usr/local/rvm/gems/ruby-1.9.3-p392@redmine233/gems/activerecord-3.2.13/lib/active_record/attribute_assignment.rb:88:in `block in assign_attributes'
/usr/local/rvm/gems/ruby-1.9.3-p392@redmine233/gems/activerecord-3.2.13/lib/active_record/attribute_assignment.rb:78:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p392@redmine233/gems/activerecord-3.2.13/lib/active_record/attribute_assignment.rb:78:in `assign_attributes'
/usr/local/rvm/gems/ruby-1.9.3-p392@redmine233/gems/activerecord-3.2.13/lib/active_record/base.rb:498:in `initialize'
/usr/local/rvm/gems/ruby-1.9.3-p392@redmine233/gems/activerecord-3.2.13/lib/active_record/validations.rb:39:in `new'
/usr/local/rvm/gems/ruby-1.9.3-p392@redmine233/gems/activerecord-3.2.13/lib/active_record/validations.rb:39:in `create!'
/opt/redmine-2.3.3/plugins/redmine_app_timesheets/db/migrate/012_version_is_order.rb:13:in `up'
/usr/local/rvm/gems/ruby-1.9.3-p392@redmine233/gems/activerecord-3.2.13/lib/active_record/migration.rb:370:in `up'
....

To get around this error I removed the description field from 012_version_is_order.rb:13
field = VersionCustomField.create!(:name => "Is order", :field_format => 'bool', :is_filter => true, :is_required => true, :default_value => false)

I reran the migration successfully after this change.

After I ran the migration I:
1. created a timesheet project with time tracking
2. Configured the timesheet plugin to use that project.

After this, I'm unable to find the timesheet application.  All of the application settings are blank, and I'm not sure if I have set it up wrong of if the installation failed.

thanks.
myles.
thanks.

**Comment by Rajk-dharmvaram** [comment] 2015-02-11 09:49
I'm using Redmine 2.6.1. I've installed the plugins successfully, but seeing the same above blank screens.
![image](https://cloud.githubusercontent.com/assets/10956404/6144785/0fae87ee-b201-11e4-9b21-3c3d2f3e50b7.png)
![image](https://cloud.githubusercontent.com/assets/10956404/6144793/2492187e-b201-11e4-8507-35d5f8d23a5e.png)
![image](https://cloud.githubusercontent.com/assets/10956404/6144804/39e50844-b201-11e4-8463-8df6fba33347.png)
![image](https://cloud.githubusercontent.com/assets/10956404/6144816/4d3c4f60-b201-11e4-9748-209105b86120.png)

**Comment by maxrossello** [comment] 2015-02-11 09:57
Did you configure and save app space plugin's settings as well?
If this is the reason, then I should document this better. Please tell if it does the trick

**Comment by Rajk-dharmvaram** [comment] 2015-02-11 09:59
The last screenshot is configuration of app space plgin, even that is blank
![image](https://cloud.githubusercontent.com/assets/10956404/6144945/c2c5b360-b202-11e4-8935-996c544a3174.png)

**Comment by maxrossello** [comment] 2015-02-11 10:07
then I should try to upgrade to 2.6.1 and, if working, try an install from scratch. But I suspect some strange build independent condition which I have not been able to identify yet. You're not the first one with this problem when installing from scratch

**Comment by Rajk-dharmvaram** [comment] 2015-02-11 10:10
Thanks for your support, it'll be really helpful if you could identify the issue and help us by resolving it. You'll not be helping just me but many with this issue. This is a very useful plugin.

**Comment by maxrossello** [comment] 2015-02-21 22:14
I've done several tries to install from scratch with latest 2.6-stable Redmine branch (currently 2.6.2). The only way I can reproduce the "blank" screen in the app space settings is before running plugins migrations (rake redmine:plugins:migrate), or after if the web server is not restarted.
I even couldn't debug the situation due to its volatility.

Please make sure that you ran the plugins migrations and restarted the server.

If it doesn't still work, then please reopen the ticket, and report the database (mine is MySql) and the web server (I'm using passenger)

**Closed by maxrossello** 2015-02-21 22:14 UTC
Labels: bug
